#!/bin/bash

echo "🎯 МОНИТОРИНГ KOLS - ИТОГОВЫЙ СТАТУС"
echo "====================================="
echo ""
echo "✅ ИСПРАВЛЕНИЯ ПРИМЕНЕНЫ:"
echo "  1. ОДИН процесс KOLS (нет спама)"
echo "  2. OpenRouter API: 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"
echo "  3. TEXT_SMALL модель (исправлено 'text' → 'TEXT_SMALL')"
echo "  4. Фильтр групп: ТОЛЬКО 2643951085 и 2298297094"
echo "  5. Имя агента: KOLS_AGENT (без 'Vibee')"
echo ""
echo "🔍 КОМАНДЫ МОНИТОРИНГА:"
echo ""
echo "1️⃣ Все логи KOLS:"
echo "   tail -f /Users/playra/vibee-agent/logs/kols-no-spam.log"
echo ""
echo "2️⃣ Логи OpenRouter:"
echo "   tail -f /Users/playra/vibee-agent/logs/kols-no-spam.log | grep -i openrouter"
echo ""
echo "3️⃣ Логи LLM:"
echo "   tail -f /Users/playra/vibee-agent/logs/kols-no-spam.log | grep -i -E '(llm|текст_small|generate)'"
echo ""
echo "4️⃣ Проверка процессов:"
echo "   ps aux | grep kolsAgent | grep -v grep"
echo ""
echo "🛑 ОСТАНОВКА KOLS:"
echo "   pkill -f 'kolsAgent.json'"
echo ""
echo "====================================="
echo "🚀 KOLS ГОТОВ К РАБОТЕ!"
echo "====================================="
