#!/bin/bash
echo "🔍 МОНИТОРИНГ ЛОГОВ KOLS В РЕАЛЬНО ВРЕМЕНИ"
echo "========================================"
echo ""
echo "📊 Текущие команды:"
echo ""
echo "1️⃣ Все логи KOLS (все события):"
echo "   tail -f logs/kols-LLM-FIXED.log"
echo ""
echo "2️⃣ Только ошибки и предупреждения:"
echo "   tail -f logs/kols-LLM-FIXED.log | grep -E '(ERROR|WARNING|⚠️|❌)'"
echo ""
echo "3️⃣ Только LLM сообщения:"
echo "   tail -f logs/kols-LLM-FIXED.log | grep -E '(LLM|TEXT_SMALL|OpenRouter|generateText)' -i"
echo ""
echo "4️⃣ Последние 50 строк:"
echo "   tail -50 logs/kols-LLM-FIXED.log"
echo ""
echo "5️⃣ Поиск по слову 'prompt':"
echo "   grep -i 'prompt' logs/kols-LLM-FIXED.log"
echo ""
echo "6️⃣ Только ответы KOLS (начинающиеся с emoji):"
echo "   tail -f logs/kols-LLM-FIXED.log | grep -E '^[🎓✅❌⚠️🤖]'"
echo ""
echo "========================================"
echo "🚀 Запуск мониторинга всех LLM сообщений..."
echo "========================================"
echo ""

# Показать новые LLM сообщения в реальном времени
tail -f logs/kols-LLM-FIXED.log | grep -E "(LLM|TEXT_SMALL|OpenRouter|generateText|generateResponse|generateLLMResponse)" -i
