#!/bin/bash
# Скрипт для просмотра логов KOLS в реальном времени

echo "🔍 МОНИТОРИНГ ЛОГОВ KOLS"
echo "================================"
echo ""
echo "📊 Доступные команды просмотра:"
echo ""
echo "1️⃣ Все логи KOLS (реальное время):"
echo "   tail -f /Users/playra/vibee-agent/logs/kols-LLM-WORKING.log"
echo ""
echo "2️⃣ Только ошибки:"
echo "   tail -f /Users/playra/vibee-agent/logs/kols-LLM-WORKING.log | grep -i error"
echo ""
echo "3️⃣ Только LLM сообщения:"
echo "   tail -f /Users/playra/vibee-agent/logs/kols-LLM-WORKING.log | grep -i llm"
echo ""
echo "4️⃣ Последние 50 строк:"
echo "   tail -50 /Users/playra/vibee-agent/logs/kols-LLM-WORKING.log"
echo ""
echo "5️⃣ Поиск по ключевому слову:"
echo "   grep -i 'ваше_слово' /Users/playra/vibee-agent/logs/kols-LLM-WORKING.log"
echo ""
echo "6️⃣ Все агенты сразу:"
echo "   tail -f /Users/playra/vibee-agent/logs/*.log"
echo ""
echo "================================"
echo "🚀 Запуск мониторинга всех логов KOLS..."
echo "================================"
echo ""
tail -f /Users/playra/vibee-agent/logs/kols-LLM-WORKING.log | grep -E "(LLM|OpenRouter|runtime.useModel|handler|plugin)" -i
